// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


var Demo = 0;

var Person = 0;

var SecondPerson = 0;

exports.Demo = Demo;
exports.Person = Person;
exports.SecondPerson = SecondPerson;
/* No side effect */
